---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeName: efs-pv
  resources:
    requests:
      storage: 20Gi