---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: /home/claude/datasets/dinov2-Imagenet1k